version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    expose:
      - 5672
    restart: on-failure

  postgis:
    image: kartoza/postgis:14-3.2
    container_name: postgis
    volumes:
      - db_land:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=Alireza12851376
      - POSTGRES_DBNAME=LandMonitoring
    networks:
      - main
    expose:
      - 5432

  geoserver:
    image: kartoza/geoserver:2.20.4
    container_name: geoserver
    ports:
      - "8080:8080"
    restart: always
    environment:
      - GEOSERVER_ADMIN_USER=sedreh
      - GEOSERVER_ADMIN_PASSWORD=ABcd1234!@
    volumes:
      - geoserver_sedreh:/opt/geoserver/data_dir
      - geoserver_footprints_sedreh:/opt/footprints_dir
      - geoserver_gwc_sedreh:/opt/geoserver/data_dir/gwc
      - geoserver_letsencrypt_sedreh:/etc/letsencrypt
      - geoserver_fonts_sedreh:/opt/fonts
      - ./Server/media/:/media
    depends_on:
      - postgis
    networks:
      - main

  ai_django:
    build:
      context: ./AI_django
    command:  sh -c "python manage.py migrate image_analysis
                    && gunicorn --reload config.wsgi  --bind 0.0.0.0:8000 "
    container_name: ai_django
    depends_on:
      - postgis
      - rabbitmq
      - geoserver
      - api_django
    environment:
      - DB_HOST=postgis
      - DB_NAME=LandMonitoring
      - DB_USER=postgres
      - DB_PASS=Alireza12851376
      - DB_PORT=5432
      - DB_SCHEMA=public
      - GEOSERVER_USERNAME=sedreh
      - GEOSERVER_PASSWORD=ABcd1234!@
      - GEOSERVER_WORKSPACE=zamin2
      - GEOSERVER_NAMESPACE=localhost
      - GEOSERVER_HOST=geoserver
      - GEOSERVER_PORT=8080
      - GEOSERVER_HOST_IP=localhost
    volumes:
      - /home/ubuntu/ai_images:/ai_django/images
#      - /home/alireza/Desktop/land_monitoring/codes/AI_django:/ai_django
    expose:
      - 8000
    networks:
      - main
    restart: on-failure


  celery_worker:
    build:
      context: ./AI_django
    container_name: celery_worker
    command: celery -A config worker -l INFO
    depends_on:
      - ai_django
      - rabbitmq
      - postgis
      - geoserver
    environment:
      - DB_HOST=postgis
      - DB_NAME=LandMonitoring
      - DB_USER=postgres
      - DB_PASS=Alireza12851376
      - DB_PORT=5432
      - DB_SCHEMA=public
      - C_FORCE_ROOT=true
    networks:
      - main
    restart: on-failure

  celery_beat:
    build:
      context: ./AI_django
    container_name: celery_beat
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - ai_django
      - api_django
      - geoserver
      - rabbitmq
      - postgis
    environment:
      - DB_HOST=postgis
      - DB_NAME=LandMonitoring
      - DB_USER=postgres
      - DB_PASS=Alireza12851376
      - DB_PORT=5432
      - DB_SCHEMA=public
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always

  api_django:
    build:
      context: ./API_django
    command: sh -c "python manage.py migrate
              && python manage.py shell -c 'from authe import load'
              && gunicorn config.wsgi --bind 0.0.0.0:8001"
    container_name: api_django
    depends_on:
      - postgis
      - rabbitmq
      - geoserver
    expose:
      - 8001
    environment:
      - DB_HOST=postgis
      - DB_NAME=LandMonitoring
      - DB_USER=postgres
      - DB_PASS=Alireza12851376
      - DB_PORT=5432
      - DB_SCHEMA=public
      - ALLOW_ORIGIN=http://localhost:3000
    networks:
      - main
    restart: on-failure

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - api_django
      - ai_django
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  main:

volumes:
  db_land:
  geoserver_sedreh:
  geoserver_footprints_sedreh:
  geoserver_gwc_sedreh:
  geoserver_letsencrypt_sedreh:
  geoserver_fonts_sedreh: