# Generated by Django 4.0.4 on 2022-05-18 10:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alborz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_nam', models.CharField(max_length=20, null=True)),
                ('center', models.CharField(max_length=20, null=True)),
                ('bakhsh', models.CharField(max_length=20, null=True)),
                ('shahrestan', models.CharField(max_length=20, null=True)),
                ('ostan', models.CharField(max_length=20, null=True)),
                ('area', models.FloatField(null=True)),
                ('hectares', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32639)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('geom', models.ManyToManyField(to='authe.alborz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
